"""Types for the small pylnk3 boundary used here; the library ships no stubs."""

class Lnk:
    @property
    def path(self) -> str | None: ...

def parse(filename: str) -> Lnk: ...
def for_file(target_file: str, lnk_name: str) -> Lnk: ...
